const $=s=>document.querySelector(s), roles=['Arrow','Help','AppStarting','Wait','Crosshair','IBeam','NWPen','No','SizeAll','SizeWE','SizeNESW','UpArrow','SizeNS','SizeNWSE','Hand','Extra'], labels=['普通选择','帮助选择','后台工作','忙碌等待','精确选择','文本选择','手写','不可用','移动','水平调整','斜向 ↗↙','候选选择','垂直调整','斜向 ↖↘','链接选择','额外状态'];
let themes=[], theme='reze', size=32, role='Arrow', busy=false, timer, activeState;
async function api(path,body){const response=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-Studio-Token':window.STUDIO_TOKEN,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败');return result;}
function image(r,n=size){return `/preview/${theme}/${r}/${n}`;}
function message(text,type=''){$('#message').textContent=text;$('#message').className=type;}
function state(s){activeState=s;const a=s.active,ref=s.systemArrow;$('#current').textContent=`系统箭头画布 ${s.liveSize} px · ${s.scheme||'系统指针'}`;$('#device').textContent=`当前屏幕指针：${a?`${a.width}×${a.height}，可见 ${a.visibleWidth}×${a.visibleHeight}`:'当前隐藏'}\n系统默认箭头：${ref?`${ref.width}×${ref.height}，可见 ${ref.visibleWidth}×${ref.visibleHeight}`:'无法读取'}\n系统实时基础大小：${s.runtimeBase}（倍率 ${(s.runtimeBase/32).toFixed(2)}）\n显示 DPI：${s.dpi} · 网页像素比：${window.devicePixelRatio.toFixed(2)}`;}
function render(){const t=themes.find(t=>t.id===theme);$('#themes').innerHTML=themes.map(t=>`<button class="theme ${t.id===theme?'active':''}" data-theme="${t.id}" aria-pressed="${t.id===theme}"><img src="/preview/${t.id}/Arrow/64" alt=""><span><strong>${t.name}</strong><small>${t.sourceWidth} px 源素材</small></span></button>`).join('');$('#states').innerHTML=roles.map((r,i)=>`<button class="state ${r===role?'active':''}" data-role="${r}" aria-pressed="${r===role}"><img src="${image(r,64)}" alt=""><span>${labels[i]}</span></button>`).join('');refresh();}
function refresh(){$('#hero').src=image(role);$('#follower').src=image(role);for(const id of ['hero','follower']){const img=$('#'+id);img.style.width=(size/window.devicePixelRatio)+'px';img.style.height=(size/window.devicePixelRatio)+'px';}$('#stateLabel').textContent=labels[roles.indexOf(role)];$('#canvasSize').textContent=`${size} × ${size} px`;$('#range').value=size;$('#size').value=size;document.querySelectorAll('[data-size]').forEach(b=>b.classList.toggle('active',+b.dataset.size===size));}
function setSize(value){if(!Number.isInteger(+value)||+value<16||+value>256){message('请输入16–256之间的整数像素。','error');return false;}size=+value;message('预览已更新，点击应用才会修改系统。');refresh();return true;}
$('#range').oninput=e=>{size=+e.target.value;$('#size').value=size;$('#canvasSize').textContent=`${size} × ${size} px`;clearTimeout(timer);timer=setTimeout(refresh,80);};$('#range').onchange=()=>{clearTimeout(timer);refresh();};$('#size').onchange=e=>{if(!setSize(e.target.value))$('#size').value=size;};
$('#themes').onclick=e=>{const b=e.target.closest('[data-theme]');if(b){theme=b.dataset.theme;render();message('已切换角色，点击应用后生效。');}};
$('#states').onclick=e=>{const b=e.target.closest('[data-role]');if(b){role=b.dataset.role;render();}};
$('.presets').onclick=e=>{const b=e.target.closest('[data-size]');if(b)setSize(+b.dataset.size);};
$('.backgrounds').onclick=e=>{const b=e.target.closest('[data-bg]');if(b){$('#stage').className='stage '+b.dataset.bg;document.querySelectorAll('[data-bg]').forEach(x=>x.classList.toggle('active',x===b));}};
$('#stage').onpointermove=e=>{const box=$('#stage').getBoundingClientRect();const t=themes.find(t=>t.id===theme),r=t.roles.find(r=>r.role===role);const f=$('#follower'),px=size/window.devicePixelRatio,x=e.clientX-box.left-r.hx*px,y=e.clientY-box.top-r.hy*px;if(x<0||y<0||x+px>box.width||y+px>box.height){f.hidden=true;$('#hero').style.visibility='visible';$('#stage').style.cursor='';return;}f.hidden=false;$('#hero').style.visibility='hidden';$('#stage').style.cursor='none';f.style.left=(e.clientX-box.left-r.hx*size/window.devicePixelRatio)+'px';f.style.top=(e.clientY-box.top-r.hy*size/window.devicePixelRatio)+'px';};$('#stage').onpointerleave=()=>{$('#follower').hidden=true;$('#hero').style.visibility='visible';$('#stage').style.cursor='';};
async function action(kind,body){if(busy)return;busy=true;document.querySelectorAll('#apply,.restore-group button').forEach(b=>b.disabled=true);message(kind==='apply'?'正在生成并应用光标…':'正在恢复…');try{const data=await api(kind,body);state(data.state);message(data.message,'success');}catch(e){message(e.message,'error');}finally{busy=false;document.querySelectorAll('#apply,.restore-group button').forEach(b=>b.disabled=false);}}
$('#apply').onclick=()=>{if(setSize($('#size').value))action('apply',{theme,size});};$('#default').onclick=()=>action('reset',{mode:'default'});$('#small').onclick=()=>action('reset',{mode:'small'});
(async()=>{try{const data=await api('catalog');themes=data.themes;if(data.state.selection){theme=data.state.selection.theme;size=data.state.selection.size;}if(!themes.some(t=>t.id===theme))theme=themes[0].id;render();state(data.state);}catch(e){$('.connection').textContent='连接失败';message(e.message,'error');}})();

window.addEventListener("focus",async()=>{if(!busy){try{state(await api("state"));}catch{}}});

$('#hero').onload=()=>{const im=$('#hero');const canvas=document.createElement('canvas');canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let x0=canvas.width,y0=canvas.height,x1=-1,y1=-1;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++)if(data[(y*canvas.width+x)*4+3]>0){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}$('#canvasSize').textContent=im.naturalWidth+' px · 可见内容 '+(x1-x0+1)+'×'+(y1-y0+1);};

window.addEventListener("resize",()=>refresh());
setInterval(async()=>{if(!busy&&document.visibilityState==="visible"){try{state(await api("state"));}catch{}}},2000);
