const $=s=>document.querySelector(s), local=window.CURSOR_MODE==='local';
document.body.classList.add(local?'mode-local':'mode-online');
const ROLES=[['Arrow','普通选择','日常指向与选择'],['Help','帮助选择','查看帮助或说明'],['AppStarting','后台工作','程序仍可操作，后台处理中'],['Wait','忙碌等待','当前操作需要等待'],['Crosshair','精确选择','精确定位或选取'],['IBeam','文字输入','输入或选择文字'],['NWPen','手写','手写或笔形操作'],['No','不可用','当前操作不能执行'],['SizeAll','移动','拖动或移动对象'],['SizeWE','水平调整','左右调整宽度'],['SizeNESW','斜向调整 ↗↙','沿右上和左下调整大小'],['UpArrow','候选选择','特殊选择状态'],['SizeNS','垂直调整','上下调整高度'],['SizeNWSE','斜向调整 ↖↘','沿左上和右下调整大小'],['Hand','链接选择','链接或部分可点击控件'],['Extra','额外状态','备用扩展状态']];
let themes=[],selectedId='reze',selectedRole='Arrow',size=32,category='全部',query='',busy=false,catalogRevision=0,workspaceRevision=0,downloads={},fullRelease,toastTimer;
const originals=new Map(),rendered=new Map();
const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const theme=()=>themes.find(t=>t.id===selectedId);
function status(text,error=false){$('#status').textContent=text;$('#status').className='status'+(error?' error':'');}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2500);}
async function api(path,body){const response=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-Studio-Token':window.STUDIO_TOKEN,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败，请重试。');return result;}
async function imageFor(id,role,pixels){
  if(local)return `/preview/${id}/${role}/${pixels}`;
  const key=`${id}/${role}/${pixels}`;if(rendered.has(key))return rendered.get(key);
  const sourceKey=`${id}/${role}`;
  if(!originals.has(sourceKey))originals.set(sourceKey,new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>{originals.delete(sourceKey);reject(Error('素材加载失败，请刷新重试。'));};image.src=`/themes/${id}/${role}.png`;}));
  const image=await originals.get(sourceKey),canvas=document.createElement('canvas');canvas.width=canvas.height=pixels;const context=canvas.getContext('2d');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(image,0,0,pixels,pixels);
  const url=canvas.toDataURL('image/png');if(rendered.size>=192)rendered.delete(rendered.keys().next().value);rendered.set(key,url);return url;
}
function renderFilters(){$('#filters').innerHTML=['全部',...new Set(themes.map(t=>t.category))].map(cat=>`<button class="filter ${category===cat?'active':''}" data-category="${escape(cat)}" aria-pressed="${category===cat}">${escape(cat)}</button>`).join('');}
function renderCatalog(){
  const revision=++catalogRevision,entries=themes.filter(t=>(category==='全部'||t.category===category)&&[t.name,t.category,...t.tags,t.summary].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
  $('#resultCount').textContent=query.trim()||category!=='全部'?`显示 ${entries.length} 套，共 ${themes.length} 套角色光标`:`共 ${themes.length} 套角色光标`;
  $('#catalogGrid').innerHTML=entries.length?entries.map(t=>`<button class="catalog-card ${t.id===selectedId?'active':''}" data-id="${escape(t.id)}" aria-pressed="${t.id===selectedId}" style="--card-accent:${t.accent}"><div class="catalog-art"><img data-catalog-image="${escape(t.id)}" alt="${escape(t.name)}"><span class="catalog-state-count">16 项状态</span></div><div class="catalog-body"><div class="catalog-top"><div><h3>${escape(t.name)}</h3><div class="catalog-category">${escape(t.category)}</div></div><span class="selected-dot">${t.id===selectedId?'已选择':'查看光标'}</span></div><p>${escape(t.summary)}</p><div class="tags">${t.tags.slice(0,3).map(tag=>`<span class="tag">${escape(tag)}</span>`).join('')}</div></div></button>`).join(''):'<div class="empty">没有找到匹配的角色。换个关键词或分类试试。</div>';
  document.querySelectorAll('[data-catalog-image]').forEach(async img=>{try{const url=await imageFor(img.dataset.catalogImage,'Arrow',216);if(revision===catalogRevision)img.src=url;}catch(error){status(error.message,true);}});
}
function renderStates(){const id=selectedId;$('#states').innerHTML=ROLES.map(([role,label,desc])=>`<button class="state ${role===selectedRole?'active':''}" data-role="${role}" aria-pressed="${role===selectedRole}"><span class="check">${role===selectedRole?'✓':'↗'}</span><img data-state-image="${role}" alt=""><b>${label}</b><span>${desc}</span></button>`).join('');$('#stateCountNote').textContent='16 项状态展示 · 应用为整套系统光标';document.querySelectorAll('[data-state-image]').forEach(async img=>{try{const url=await imageFor(id,img.dataset.stateImage,144);if(selectedId===id&&img.isConnected)img.src=url;}catch(error){status(error.message,true);}});}
function resetFollower(){$('#follower').hidden=true;$('#previewImg').style.visibility='visible';$('#stage').style.cursor='';}
async function refreshWorkspace(){
  if(!themes.length)return;const revision=++workspaceRevision,t=theme();resetFollower();document.documentElement.style.setProperty('--accent',t.accent);
  $('#roleLabel').textContent=ROLES.find(r=>r[0]===selectedRole)[1];$('#previewName').textContent=`${t.name} · ${size} × ${size} px`;$('#selectedSummary').textContent=`当前角色：${t.name} · 当前状态：${ROLES.find(r=>r[0]===selectedRole)[1]} · 当前尺寸：${size} px`;$('#sizeInput').value=$('#sizeRange').value=size;
  document.querySelectorAll('[data-size]').forEach(b=>b.classList.toggle('active',+b.dataset.size===size));document.querySelectorAll('[data-role]').forEach(b=>{const active=b.dataset.role===selectedRole;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);b.querySelector('.check').textContent=active?'✓':'↗';});
  for(const id of ['previewImg','follower']){const img=$('#'+id);img.style.width=img.style.height=(size/window.devicePixelRatio)+'px';}
  if(!local){const pack=downloads[selectedId];$('#singleDownload').hidden=!pack;if(pack){$('#singleDownload').href=pack.url;$('#singleDownload').download=pack.filename;$('#singleDownload').textContent=`下载早期独立包 ${pack.version}`;}}
  try{const url=await imageFor(selectedId,selectedRole,size);if(revision===workspaceRevision)$('#previewImg').src=$('#follower').src=url;}catch(error){if(revision===workspaceRevision)status(error.message,true);}
}
function setSize(value){const pixels=Number(value);if(!Number.isInteger(pixels)||pixels<16||pixels>256){$('#sizeInput').value=size;status('请输入16–256之间的整数像素。',true);return false;}size=pixels;refreshWorkspace();status(local?'预览已更新，点击应用后才会修改系统。':'预览已更新，下载后在本地工作台应用所需尺寸。');return true;}
function showDevice(state){if(!local){$('#deviceInfo').textContent=`网页像素比：${window.devicePixelRatio.toFixed(2)}。预览按屏幕物理像素换算；画布包含透明留白。在线页面无法读取 Windows 光标方案、实时系统光标尺寸或显示 DPI，也无法修改 Windows 设置。`;return;}const a=state.active,ref=state.systemArrow;$('#deviceInfo').textContent=`当前 Windows 光标方案：${state.scheme||'系统光标'}\n实时光标画布：${state.liveSize} px\n当前可见指针：${a?`${a.visibleWidth} × ${a.visibleHeight} px`:'隐藏'}\n系统默认箭头：${ref?`${ref.width} × ${ref.height}，可见 ${ref.visibleWidth} × ${ref.visibleHeight}`:'无法读取'}\nWindows 光标基础大小：${state.runtimeBase}（倍率 ${(state.runtimeBase/32).toFixed(2)}）\n显示DPI：${state.dpi} · 网页像素比：${window.devicePixelRatio.toFixed(2)}`;}
async function action(kind,body){if(busy)return;busy=true;for(const id of ['applyBtn','resetBtn','smallBtn'])$('#'+id).disabled=true;status(kind==='apply'?'正在应用整套光标…':'正在恢复系统光标…');try{const data=await api(kind,body);showDevice(data.state);status(data.message);toast(data.message);}catch(error){status(error.message,true);toast(error.message);}finally{busy=false;for(const id of ['applyBtn','resetBtn','smallBtn'])$('#'+id).disabled=false;}}
$('#searchInput').oninput=e=>{query=e.target.value;renderCatalog();};
$('#filters').onclick=e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;renderFilters();renderCatalog();}};
$('#catalogGrid').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;selectedId=b.dataset.id;selectedRole='Arrow';renderCatalog();renderStates();refreshWorkspace();status(`已选择「${theme().name}」，当前只是预览。`);$('#workspace').scrollIntoView({behavior:'smooth',block:'start'});};
$('#states').onclick=e=>{const b=e.target.closest('[data-role]');if(b){selectedRole=b.dataset.role;refreshWorkspace();}};
$('#sizeRange').oninput=e=>setSize(e.target.value);$('#sizeInput').onchange=e=>setSize(e.target.value);
$('.presets').onclick=e=>{const b=e.target.closest('[data-size]');if(b)setSize(b.dataset.size);};
$('.segment').onclick=e=>{const b=e.target.closest('[data-bg]');if(b){$('#stage').className='stage '+b.dataset.bg;document.querySelectorAll('[data-bg]').forEach(x=>x.classList.toggle('active',x===b));}};
$('#stage').onpointermove=e=>{if(e.pointerType!=='mouse'||!themes.length)return;const box=$('#stage').getBoundingClientRect(),hotspot=theme().roles.find(r=>r.role===selectedRole),width=size/window.devicePixelRatio,x=e.clientX-box.left-hotspot.hx*width,y=e.clientY-box.top-hotspot.hy*width;if(x<0||y<0||x+width>box.width||y+width>box.height){resetFollower();return;}$('#follower').style.left=x+'px';$('#follower').style.top=y+'px';$('#follower').hidden=false;$('#previewImg').style.visibility='hidden';$('#stage').style.cursor='none';};
$('#stage').onpointerleave=resetFollower;
$('#applyBtn').onclick=()=>{if(local){if(setSize($('#sizeInput').value))action('apply',{theme:selectedId,size});}else if(fullRelease){window.location.assign(fullRelease.url);}};
$('#resetBtn').onclick=()=>action('reset',{mode:'default'});$('#smallBtn').onclick=()=>action('reset',{mode:'small'});
window.addEventListener('resize',()=>{refreshWorkspace();if(!local)showDevice();});$('#previewImg').onerror=()=>status('预览加载失败，请重新选择角色或刷新页面。',true);
(async()=>{try{let data;if(local){data=await api('catalog');themes=data.themes;if(data.state.selection){selectedId=data.state.selection.theme;size=data.state.selection.size;}showDevice(data.state);}else{const response=await fetch('/catalog.json');if(!response.ok)throw Error('无法加载角色目录，请刷新重试。');data=await response.json();({themes,downloads,fullRelease}=data);$('#modeBadge').innerHTML='<i></i> 在线预览 · 完整包下载';$('.brand-sub').textContent='CURSOR LIBRARY';$('#applyBtn').textContent=`下载完整合集 V${fullRelease.version}`;$('#resetBtn').hidden=$('#smallBtn').hidden=true;$('#singleDownload').hidden=false;$('#helper').textContent='在线调整尺寸只影响预览，不会修改 Windows 设置，也不会改变下载包的默认尺寸。下载后在本地工作台应用所需尺寸。';$('#introCopy').textContent='Windows 角色光标预览与安装工具。在角色目录中选择角色，查看各个光标状态，调整尺寸，并下载整套光标。在线版本用于预览和下载，本地版本可直接应用到 Windows。';showDevice();}themes=themes.map(t=>({...t,category:t.category||'角色',tags:t.tags||[],summary:t.summary||'整套角色光标，随时切换。',accent:/^#[0-9a-f]{6}$/i.test(t.accent||'')?t.accent:'#7157e8'}));if(!themes.some(t=>t.id===selectedId))selectedId=themes[0].id;if(!Number.isInteger(size)||size<16||size>256)size=32;renderFilters();renderCatalog();renderStates();refreshWorkspace();status(local?'当前只是预览，点击应用后才会修改系统。':'在线预览不会修改系统。完整解压安装包后，双击「一键安装.cmd」。');}catch(error){status(error.message,true);$('#applyBtn').disabled=true;$('#modeBadge').textContent='加载失败，请刷新重试';}})();
if(local){const update=async()=>{if(!busy&&document.visibilityState==='visible'){try{showDevice(await api('state'));}catch{}}};window.addEventListener('focus',update);setInterval(update,2000);}
